import { DB_Fetch, Tables } from "@/db";
import { JsonResponse } from "@/helper/api";
import { sql } from "drizzle-orm";

/**
 * Checks the settings table to see if the registration ID auto-generation is configured.
 * Returns true if the setting exists and has a valid format (PREFIX,DIGITS).
 */
export async function GET(req) {
    try {
        let isAutoGenerated = false;

        // 1. Fetch the setting value from the database
        const settingResults = await DB_Fetch(sql`
            SELECT value FROM ${sql.identifier(Tables.TBL_SETTINGS)}
            WHERE setting_group = 'general' AND field_name = 'regn_no'
        `);

        console.log("Fetched Regn No Setting Results: ", settingResults);

        const settingValue = settingResults?.[0]?.value;

        console.log("Fetched Regn No Setting Value: ", settingValue);
        if (settingValue) {
            // Expected format: "PREFIX,DIGITS" (e.g., "EMP,4")
            const [prefix, digitsStr] = settingValue.split(',');
            const digits = parseInt(digitsStr, 10);

            // 2. Validate the format
            if (prefix && !isNaN(digits) && digits > 0) {
                isAutoGenerated = true;
            }
        }

        // 3. Return the status to the frontend
        return JsonResponse.success(
            { isAutoGenerated: isAutoGenerated },
            "Registration ID setting status retrieved successfully."
        );

    } catch (error) {
        console.error("[api/settings/registration-id-status] Error:", error);
        
        // In case of any database error, default to manual entry required (isAutoGenerated: false)
        return JsonResponse.error("Error retrieving configuration settings.", 500, {
            isAutoGenerated: false
        });
    }
}